# Generated by Django 4.0.5 on 2022-06-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffresident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='change_password',
            field=models.BooleanField(default=False),
        ),
    ]
