# Generated by Django 4.0.5 on 2022-06-22 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffresident', '0003_rolesstaff_alter_staffrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrole',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='staff_data', to='staffresident.rolesstaff'),
        ),
    ]
