# Generated by Django 4.0.5 on 2022-06-22 09:53

from django.db import migrations
import staffresident.models


class Migration(migrations.Migration):

    dependencies = [
        ('staffresident', '0004_alter_staffrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesstaff',
            name='rolename',
            field=staffresident.models.CICharField(max_length=50, unique=True),
        ),
    ]
