# Generated by Django 4.0.5 on 2022-06-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0005_alter_userrole_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateTimeField(auto_now=True)),
                ('next_pay_date', models.DateField()),
            ],
        ),
    ]
