# Generated by Django 4.0.5 on 2022-06-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0006_userpaymaintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymaintenance',
            name='pay_date',
        ),
    ]
