# Generated by Django 4.0.5 on 2022-06-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0007_remove_userpaymaintenance_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymaintenance',
            name='pay_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
