# Generated by Django 4.0.5 on 2022-06-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0008_userpaymaintenance_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymaintenance',
            name='amount_pay',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpaymaintenance',
            name='house_no',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
