# Generated by Django 4.0.5 on 2022-06-29 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0009_userpaymaintenance_amount_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpaymaintenance',
            name='pay_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
