# Generated by Django 4.0.5 on 2022-07-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0011_remove_userpaymaintenance_next_pay_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpaymaintenance',
            name='is_complete_pay',
            field=models.BooleanField(default=False),
        ),
    ]
