# Generated by Django 4.0.5 on 2022-07-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0012_userpaymaintenance_is_complete_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountPayMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pay', models.IntegerField()),
            ],
        ),
    ]
