# Generated by Django 4.0.5 on 2022-07-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0013_amountpaymaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountpaymaintenance',
            name='amount_pay',
            field=models.CharField(max_length=10),
        ),
    ]
