# Generated by Django 4.0.5 on 2022-06-22 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_remove_visitorssociety_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorssociety',
            name='user',
        ),
    ]
