# Generated by Django 4.0.5 on 2022-06-22 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffresident', '0005_alter_rolesstaff_rolename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitors', '0003_remove_visitorssociety_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorssociety',
            name='staff',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='staffresident.staffrole'),
        ),
        migrations.AddField(
            model_name='visitorssociety',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
