# Generated by Django 4.0.5 on 2022-06-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffresident', '0005_alter_rolesstaff_rolename'),
        ('resident', '0005_alter_userrole_user'),
        ('visitors', '0005_alter_visitorssociety_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorssociety',
            name='staff',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffresident.staffrole'),
        ),
        migrations.AlterField(
            model_name='visitorssociety',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='resident.userrole'),
        ),
    ]
