# Generated by Django 4.0.5 on 2022-06-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0006_alter_visitorssociety_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorssociety',
            name='is_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Reject', 'Reject'), ('Unverified', 'Unverified')], default='Unverified', max_length=15),
        ),
    ]
