# Generated by Django 4.0.5 on 2022-06-28 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_visitorssociety_is_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorssociety',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
