# Generated by Django 4.0.5 on 2022-06-30 06:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0009_visitorssociety_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitorsSociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('profile_pics', models.ImageField(upload_to='profile_pics')),
                ('addharcard_number', models.CharField(max_length=16)),
            ],
        ),
    ]
