# Generated by Django 4.0.5 on 2022-07-01 04:46

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0012_alter_dailyvisitorssociety_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorssociety',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
